export const ActivityAction = {
  AUTH_LOGIN: 'auth.login',
  AUTH_LOGOUT: 'auth.logout',
  COMPANY_CREATE: 'company.create',
  COMPANY_UPDATE: 'company.update',
  COMPANY_DELETE: 'company.delete',
  COMPANY_RESTORE: 'company.restore',
  COMPANY_HARD_DELETE: 'company.hard_delete',
  COMPANY_USER_ADD: 'company.user_add',
  COMPANY_USER_REMOVE: 'company.user_remove',
  COMPANY_USER_UPDATE: 'company.user_update',
  SOCIAL_ACCOUNT_CREATE: 'social_account.create',
  SOCIAL_ACCOUNT_UPDATE: 'social_account.update',
  SOCIAL_ACCOUNT_DELETE: 'social_account.delete',
  CONTENT_CREATE: 'content.create',
  CONTENT_UPDATE: 'content.update',
  CONTENT_DELETE: 'content.delete',
  CONTENT_STATUS_CHANGE: 'content.status_change',
  CONTENT_ASSIGN: 'content.assign',
  CONTENT_APPROVE: 'content.approve',
  CONTENT_REJECT: 'content.reject',
  PAYMENT_CREATE: 'payment.create',
  PAYMENT_UPDATE: 'payment.update',
  PAYMENT_STATUS_CHANGE: 'payment.status_change',
  PAYMENT_DELETE: 'payment.delete',
} as const;
